site_name: Tarea 2 | Cuadratura Gaussiana

theme:
  name: material

nav:
  - Introducción: index.md
  - Método Numérico: explanation.md
  - Tutorial: tutorials.md
  - Referencia: reference.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

